id: P008009
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:54:58.700856
source_metadata:
  id: bdr:W2CZ7977
  title: ནམ་མཁའ་རྒྱལ་མཚན་གྱི་གསང་བའི་རྣམ་ཐར་ལུང་བསྟན་དང་བཅས་པ
  author: ''
  volumes:
    ea98cc8785ce4fcaac659a948da773b1:
      image_group_id: I1KG3773
      title: Volume 1 of gsang ba'i rnam thar lung bstan dang bcas pa
      volume_number: 1
      total_pages: 40
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
