id: P008009
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ7977
  title: ནམ་མཁའ་རྒྱལ་མཚན་གྱི་གསང་བའི་རྣམ་ཐར་ལུང་བསྟན་དང་བཅས་པ
  author: ''
  volumes:
    d800ce20a5464580b3b9a11641bcd293:
      image_group_id: I1KG3773
      title: ''
      volume_number: 1
      total_pages: 40
ebook_metadata:
  title: ནམ་མཁའ་རྒྱལ་མཚན་གྱི་གསང་བའི་རྣམ་ཐར་ལུང་བསྟན་དང་བཅས་པ
  author: ''
  sku: P008009
  cover: cover.jpg
  layers:
  - pagination
